name: apollo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.5.0
  permission_handler: ^3.1.0
  cupertino_icons: ^0.1.2
  launcher_assist: ^1.1.3
  wifi_iot:
    path: ../flutterwifi
  
  screen: ^0.0.5
  bubble_tab_indicator: ^0.1.4
  flutter_xlider: ^2.5.0
  volume: ^0.1.0
  expandable_bottom_bar: ^0.1.1
  rubber: ^0.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

 
  uses-material-design: true

  assets:
        - assets/1.jpg
        - assets/faces/32.jpg